version: 0.2

env:
  variables:
    VARIANT: "fcbls"
    BUILD_TARGETS: "qemu"
    BUILD_COMMAND: "build-grubless"

phases:
  install:
    commands:
      - git config --global --add safe.directory /codebuild/output/srcDownload/src
      - git submodule update --init
      - scripts/install/01_hydrate_links.sh
      - scripts/install/05_create_repo.sh
  pre_build:
    commands:
      - scripts/pre_build/01_cosa_clean.sh
  build:
    commands:
      - scripts/build/05_build_images.sh
artifacts:
  files:
    - builds/latest/x86_64/*
    - builds/builds.json
  discard-paths: no
